### PR TITLE
Timestep limiter for gravity waves

### PR DESCRIPTION
**Pull request by higl**
my base is quite a few commits behind, but i hope the merge is not that complicated, because i mainly added things.

For the msconvect problem i also created a new general null network, which uses hydrogen, helium and assumes that all the metals are in form of CNO elements, which have an average A and Z corresponding to the solar abundances of CNO elements.
[aproxCNOsolar.net.zip](https://github.com/AMReX-Astro/MAESTRO/files/1075079/aproxCNOsolar.net.zip)

### CODE REVIEW

**Comment by zingale** [comment]
I changed the base to `development` -- we typically merge into `development`, since that's where the test suite runs, and then we merge `development` -> `master` monthly

**Comment by zingale** [comment]
can you remove the changes to `test_eos`, `subchandra`, and `wdconvect`?  I don't think that those should be changed.

**Comment by adam-m-jcbs** [comment]
Hey Johann, thanks for contributing to Maestro!

I'm going through and making notes via git on your commits.  They should pop up in this feed.  Please review these.

**Comment by adam-m-jcbs** [comment]
Hi Johann.  Thanks for contributing to and using Maestro!

Below are my comments on your commits.


- commit ad6fc8ec154:
Looks good.

Note that NDEBUG is only ever checked to see if it has a value or not. So NDEBUG := f has the same impact as NDEBUG := t. The variable is an unfortunately named bit of legacy. Typically, we use NDEBUG = t to do the build without debug flags (e.g. -g) and we use NDEBUG = (set it to be empty) to do a build with debugging.


- commit 9a03ed94230:
Requires change.

wdconvect shouldn't be modified


- commit 963c1ae15a4:
Requires change.

Mostly good in that it's all stuff dealing with your new problem.  However, there are some changes to sub_chandra that shouldn't be there. There are various other issues requiring resolving:

Util/initial_models/lagrangian_planar/helm_table.dat is pointing to your local system's helm_table.

Util/initial_models/lagrangian_planar/init_1d.f90: You use your own definition of PI, but you should use the `bl_constants_module`'s `M_PI`

Util/initial_models/lagrangian_planar/network.f90: This is build-generated file and shouldn't be committed.

Util/initial_models/spherical/GNUmakefile: Instead of editing the GNUmakefile, for variations of the makefile that not everyone will use we tend to pass the args via make.  e.g. instead of editing the file like you have here, you could do something like
`make GENERAL_NET_INPUTS=$(MICROPHYSICS_DIR)/networks/$(NETWORK_DIR)/aproxMS.net`

Util/initial_models/spherical/_params: I might suggest adding your own `_params` file instead of editing the one already there.  e.g. make `_params.aproxms` or some such. 

Util/initial_models/spherical/helm_table.dat: seems to be pointing to your local filesystem's helm_table.

Util/initial_models/spherical/init_1d.f90: To match Maestro conventions, it would be nice to keep the leading `i` for species indices, e.g. `ih1` instead of `h1`.  Also, like with params you might consider making your own init_1d.f90 for your problems instead of changing the current init_1d.f90.  Ideally, changes to it will be applicable to any problem.

Util/initial_models/spherical/network.f90: Another build-generated file that shouldn't be committed.

Util/initial_models/spherical/test.hse.1280: The model data should be kept in the problem directory, not in the utility directory.


-commit c0b630f0b75e8:

The test you do in `Source/geometry.f90` is
```
    ! check if the base cutoff coordinate is at the edge of the model
￼     if (base_cutoff_density_coord(1) .eq. nr(1)) then
￼       call bl_error("base_cutoff_density lower than outermost density of model")
￼     endif
```
I'm not sure if this is guaranteed to do what you would like.  I'm wondering what @zingale thinks.


-commit ee230f0eaae:
Just cleanups, so good.


-commit a95221f58e19204648721:
Most of this modified your science problem, which should have no adverse impacts on Maestro.  However, some changes are needed:

Exec/SCIENCE/msconvect/Input_Models/3.5msolar.mod: Compiled files shouldn't be added to the repo.

Exec/SCIENCE/msconvect/network.f90: Build-generated files shouldn't be added to the repo.


-commit 070b4b5dbc5ab
Only modifies your problem, so no issues.


-commit 68c8998364c:
Some changes needed: 

Exec/UNIT_TESTS/test_eos/network.f90: Build-generated files shouldn't be added to the repo.

Util/initial_models/lagrangian_planar/GNUmakefile: Instead of editing the GNUmakefile, for variations of the makefile that not everyone will use we tend to pass the args via make.  See previous comment about this.

Util/initial_models/lagrangian_planar/init_1d.f90: see previous comments on files like this.

Util/initial_models/lagrangian_spherical/network.f90: Build-generated files shouldn't be added to the repo.

@zingale Note this adds a new spherical version of Lagrangian init 1d.  You might want to check it out.


-commit e7a8590a5f3895:
@zingale This makes some changes to the main source and parameters.  You may want to take a look. My skimming of it doesn't turn up any issues beyond what I've already commented on above.


-commit a68a76a46191:
Only makes changes to the new Source/make_brunt_freq.f90 and Source/make_hp.f90, so should be fine, depending on Mike's comments on commit e7a8590a5f3895.


-commit c2c8d54000c7:
@zingale This adds new functionality for binary input.  You might want to take a look.

Util/initial_models/lagrangian_spherical/network.f90: Build-generated files shouldn't be added to the repo.


-commit 59b5e25a9307:
See previous init_1d comments.


-commit d7edf133fe9:
No comments beyond those that I had for commit e7a8590a5f3895...


-commit 924099fc38c8:
Changes to your problem and continuing developments in 
Source/estdt.f90, and
Source/make_brunt_freq.f90 .
No new comments.


-commit 0a6b438:
Shouldn't change test_eos.


-commit 4bc90cbfb580:
More changes to primary source.  We should look into running the test suite on this code.


-commit 7c8e1ffe0e9:
Only changes your problem, so no issues.


-commit 3d7c603540:
See previous comments on modifications of code in Source.


-commit 4680e0358:
Minor change, no new comments.


-commit 05cad172d6cd:
Minor change, no new comments.

-commit 009921738f6b38e648:
Minor changes, no new comments.


-commit ce2e9fa7f72587:
Only changes your problem, no issues.

**Comment by adam-m-jcbs** [comment]
In summary, the major issues I noticed:

- network.f90 should not generally be added to the git repo.  This file is generated at build time.

- As much as possible, avoid changing files outside of your problem and try to make changes to shared files (like those in Source) robust and generally useful for all problems.

- Some of your init_1d stuff seems particular to your problem but is not in a problem-specific directory.  I'm not sure if we have a policy on developing init_1d code specific to a problem.  I wonder what @zingale's thoughts are.

- Some significant changes have been made to Source, namely in:
Source/GPackage.mak
Source/_parameters
Source/base_state.f90
Source/enforce_HSE.f90
Source/estdt.f90
Source/make_brunt_freq.f90
Source/make_grav.f90
Source/make_plotfile.f90
Source/make_scale.f90
Source/make_w0.f90
Source/probin.template
Source/variables.f90

These may be all fine.  However, we should run the test-suite on this code to see if anything broke.  And perhaps @zingale can skim your changes to see if he has any recommendations on how to write changes in a "maestronic" way.

**Comment by higl** [comment]
Hi,
thanks for the comments. 
I removed the changes which do not touch my problem directly. This includes wdconvect, subchandra, everything in /TEST_PROBLEMS, and the langrangian_spherical routine for the input models. I updated those to the current commit in the upstream.

The langrangian_spherical routine could be added at a later point, but at the moment the smoothing part (which is essentially taken from the Gilet paper) is not working too well. Once this is fixed and I added options to change the stratification of the initial model in there and then it might be worth adding it.

Without the test in c0b630f you run outside of an array in make_w0.f90. In commit d7edf13 I added a proper bugfix for that, which allows to run simulations where the cutoff_density is outside the actual domain. However, I'm not sure if this is something we should allow at all, but then at least the test of c0b630f should be included.

Commit 4bc90cb is my quick attempt to allow for (planar) simulations that exclude the centre of the model. I also renamed do_2d_planar_octant to do_self_grav, as I think that is more intuitive. 

Exec/SCIENCE/msconvect/Input_Models/3.5msolar.mod is an output file of our 1D evolution code. It should be there as it contains all the information of the other files with higher precision.

**Pull request closed without merging**
