### PR TITLE
add developer information including core developers, sync with Castro

### PR DESCRIPTION
**Pull request by zingale**
this explains the process to become a "core developer"

### CODE REVIEW

**Comment by zingale** [comment]
@adam-m-jcbs ^

**Comment by dwillcox** [comment]
This all seems very reasonable to me, a couple things came to mind:

- Does a "non-merge commit" mean a commit that was pushed directly to the repo and not submitted as a PR? That's how it reads to me but just checking, since that suggests contributions via PR would only be evaluated based on the second criteria, "addition of a new algorithm/module".

- Can we add a line pointing users to Microphysics, perhaps in the Getting Started section below the link to AMReX?

**Comment by maxpkatz** [comment]
> Does a "non-merge commit" mean a commit that was pushed directly to the repo and not submitted as a PR?

No. It means a commit that actually adds/removes content, not the commits that merge one branch into another.

**Comment by dwillcox** [comment]
I see, and that makes more sense than my interpretation.

If it's generally unambiguous then I'll accept that, otherwise I would recommend rewording "non-merge commits" to "source-modifying commits" or something along those lines.

**Comment by zingale** [comment]
"merge commit" is a pretty standard  term, so I'd like to leave it at that.  I'll add the Microphysics link

**Pull request merged**
